server:
  port: 9001
  context-path: /api/
spring:
  cloud:
    config:
      enabled: false
  ##datasource:
  ##  url: jdbc:mysql://127.0.0.1/pos_db
  ##  username: root
  ##  password: password
  ##  driver-class-name: com.mysql.jdbc.Driver
logging:
  level: DEBUG
  config: classpath:log4j2-${spring.profiles.active}.yml
  jackson:
    serialization-inclusion: NON_NULL