spring:
  application:
    name: webtest
  profiles:
    active: mac
  boot:
    admin:
      url: http://localhost:8080
      #api-path: wstest
      client:
        enabled: true
  cloud:
    config:
      enabled: false
endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: true
security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin
logging:
 config: file:/Proyectos/Apps/config/log4j2-${spring.profiles.active}.yml      