info:
  version: 1.0
  stage: test
  
spring:
  application:
    name: wstest
  profiles:
    active: mac
  boot:
    admin:
      client:
        enabled: true
        service-url: http://localhost:9080/wstest
      url: http://localhost:8080
      username: admin
      password: admin
      #api-path: wstest